export enum StepNames {
  ApplicationDate = 'Дата обращения',
  Name = 'ФИО',
  Male = 'Пол',
  SessionDate = 'Дата сеанса',
  Link = 'Ссылка',
  Source = 'Источник',
  Phone = 'Номер телефона',
  Sketch = 'Эскиз',
  PaymentMade = 'Внесенная оплата',
  Payment = 'Стоимость',
  Status = 'Статус',
  City = 'Город',
  Comment = 'Комментарий',
}
